spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: create #todo: change to update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: ${SPRING_JPA_DATABASE}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  qr-code:
    path: ${APPLICATION_QR_CODE_PATH}

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]


stripe:
    secret-key: ${STRIPE_SECRET_KEY}
    price10: ${STRIPE_PRICE10}
    price15: ${STRIPE_PRICE15}